//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViajArt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tours
    {
        public int TourID { get; set; }
        public string Nombre { get; set; }
        public int PaisID { get; set; }
        public int DestinoID { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public decimal Precio { get; set; }
        public Nullable<decimal> ITBIS { get; set; }
        public int DuracionDias { get; set; }
        public int DuracionHoras { get; set; }
        public Nullable<System.DateTime> FechaHoraFin { get; set; }
        public string Estado { get; set; }
    
        public virtual Destinos Destinos { get; set; }
        public virtual Pais Pais { get; set; }
    }
}
